### ISSUE TITLE
main.pyのactionの値について

### ISSUE THREAD

**Issue by TakaraKait0** [KaedeYamazaki/Let-s-try-reward-design#1]
unity内のagentの移動にactionを使用しています。slipが発生したとき、stateはそれに応じて変化しているようですが、actionが何故か変化していません。プロンプトに表示される空間は正しいようですが、main.pyでactionの値を表示すると、バグがあります。
![Screenshot from 2024-07-05 02-27-07](https://github.com/KaedeYamazaki/Let-s-try-reward-design/assets/137743157/606e853f-83c7-484d-85f1-49efa8ca0cde)

**Comment by TakaraKait0** [comment]
このバグが修正されれば、主な動作は完成

**Comment by KaedeYamazaki** [comment]
まずdecide_actionの返り値を利用してunity側で反映させるということで，よろしいでしょうか？
今回，slipする環境でゴールに効率よく到達するタスクですので，環境の影響とエージェントの行動決定(decide_action)とは切り離していました．

unityとの連携のために，stepにおいて，slipし変化したactionのindexの情報を返すように修正しますね．

**Comment by KaedeYamazaki** [comment]
以下のように修正しました．

OC_Cliff_Walking.py
![image](https://github.com/KaedeYamazaki/Let-s-try-reward-design/assets/102452664/a93f6b86-f6ef-4228-8c5f-42ab7df37dde)

main.py
![image](https://github.com/KaedeYamazaki/Let-s-try-reward-design/assets/102452664/3b9b5ae1-7e11-482c-9c70-beac7346bd46)
